# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6de94546461a7688b511b0b9f0b128959d5d589d6453ef9a4ed726f90b48d9e05f63fb4d2a9520c3b063040d07763c53bbbc15cf5e0c8569f67c3f05b241d2e

test:
  secret_key_base: f3a56e14d3e0d3d0d2828a44021852ce342107cb411c4d8dd1eda7bc2bf09df8aeda2679f7da547633e18b76ca93caed0d02dd61d80590df1f26c04d801cf223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
